### ISSUE TITLE
《Flutter 入门指南》1.0.0 版本配套Demo重写计划

### ISSUE THREAD

**Issue by icepy** [icepy/flutter-dress#1]
- ~~token + 用户密码的Github校验（不上传），解决API调用限制问题~~
- 完善启动页面
- 显示 issues
- 优化展示女装列表
- 显示 PR 列表
- 提供秘迹搜索服务（隐私搜索）
- 优化女装详情页
- 提供收藏功能和图片下载

**Comment by manooog** [comment]
分一些功能我做蛤……

**Comment by icepy** [comment]
> 分一些功能我做蛤……

好，没问题

**Comment by icepy** [comment]
> * token + 用户密码的Github校验（不上传），解决API调用限制问题
> * 完善启动页面
> * 显示 issues
> * 优化展示女装列表
> * 显示 PR 列表
> * 提供秘迹搜索服务（隐私搜索）
> * 优化女装详情页
> * 提供收藏功能和图片下载

仔细阅读了一下文档，token + 基础认证这个方式需要一个后台服务来存储token，不然token会发生丢失的情况。这对于演示应用来说，还需要写一个服务来管理token，明显比较重，因此放弃授权，依然沿用之前被限制的调用，60/H。

**Comment by manooog** [comment]
> > * token + 用户密码的Github校验（不上传），解决API调用限制问题
> > * 完善启动页面
> > * 显示 issues
> > * 优化展示女装列表
> > * 显示 PR 列表
> > * 提供秘迹搜索服务（隐私搜索）
> > * 优化女装详情页
> > * 提供收藏功能和图片下载
> 
> 仔细阅读了一下文档，token + 基础认证这个方式需要一个后台服务来存储token，不然token会发生丢失的情况。这对于演示应用来说，还需要写一个服务来管理token，明显比较重，因此放弃授权，依然沿用之前被限制的调用，60/H。

我选择 显示 issues 和 显示 pr 列表 两个模块

**Comment by sichenguo** [comment]
> * token + 用户密码的Github校验（不上传），解决API调用限制问题
> * 完善启动页面
> * 显示 issues
> * 优化展示女装列表
> * 显示 PR 列表
> * 提供秘迹搜索服务（隐私搜索）
> * 优化女装详情页
> * 提供收藏功能和图片下载

可以认领个优化列表页的任务吗

**Comment by icepy** [comment]
> > * token + 用户密码的Github校验（不上传），解决API调用限制问题
> > * 完善启动页面
> > * 显示 issues
> > * 优化展示女装列表
> > * 显示 PR 列表
> > * 提供秘迹搜索服务（隐私搜索）
> > * 优化女装详情页
> > * 提供收藏功能和图片下载
> 
> 可以认领个优化列表页的任务吗

是优化展示女装列表吗？这里有一个收藏，会牵扯到本地存储和bloc，你可以先试一试；
